name: phoenix1

services:
  phoenix:
    type: compose
    scanner: false
    app_mount: delegated
    services:
      image: elixir:1.16.2-slim
      command: tail -f /dev/null
    volumes:
      phoenix:
    build_as_root:
      - DEBIAN_FRONTEND=noninteractive apt update -y && apt install -yq git # TODO this still requires user interaction + inotify-tools missing
    build:
      - mix archive.install hex phx_new --force 

  database:
    type: postgres:15
    portforward: 5432
    creds:
      database: phoenix1
      user: postgres
      # By "NO PASSWORD" we mean the password is blank
      password: NO PASSWORD

  # It could take up to 30 seconds until pgAadmin starts.
  # Until it's loaded, it will give you Bad Gateway, so be patient.
  # pgAdmin login: admin@admin.com
  # pgAdminpassword: root
  #
  # Connect to PostgreSQL
  # host: database
  # port: 5432
  # database: drupalpostgrespgadmin
  # user: postgres
  # (there is no password)
  #
  # Source: https://github.com/lando/lando/issues/1991#issuecomment-967760888
  pgadmin:
    api: 3
    type: lando
    app_mount: delegated
    scanner: false
    services:
      image: dpage/pgadmin4:8.4
      command: "/entrypoint.sh"
      ports:
        - '80'
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
        PGADMIN_LISTEN_ADDRESS: 0.0.0.0
        PGADMIN_LISTEN_PORT: 80
        PGADMIN_SERVER_JSON_FILE: /app/.lando/pgadmin/servers.json

proxy:
  phoenix:
    - phoenix1.localhost
  pgadmin:
    - pma.phoenix1.localhost

tooling:
  mix:
    service: phoenix
  elixir:
    service: phoenix  
  iex:
    service: phoenix
  psql:
    service: database

# - Create project (instead of hello, give it another name)
# lando mix phx.new hello --force
# cd hello (or the another name)
# lando mix deps.get
# now set 0.0.0.0 instead of 127.0.0.1 in config/config.exs as url: [host: "0.0.0.0"],
# now set in config/config.exs as  http: [ip: {0, 0, 0, 0}, port: 80],
# now set db credentials in config/dev.exs config/test.exs
# lando mix ecto.create

# - Run server
# lando mix phx.server
#   or 
# lando iex -S mix phx.server