name: mssql

services:
  database:
    scanner: false
    api: 3
    type: lando
    services:
      user: root
      image: mcr.microsoft.com/mssql/server:2022-CU19-ubuntu-22.04
      command: /opt/mssql/bin/sqlservr
      volumes:
        - mssql:/var/opt/mssql
      ports:
        - 1433
      environment:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: he11oTHERE
    volumes:
      mssql:

  adminer:
    scanner: false
    api: 3
    type: lando
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    portforward: true

  cloudbeaver:
    scanner: false
    api: 3
    type: lando
    services:
      image: dbeaver/cloudbeaver:25.1.2
      command: /opt/cloudbeaver/launch-product.sh
      ports:
        - 8978
      volumes:
        - "./.lando/cloudbeaver/logs:/opt/cloudbeaver/logs"
        - "./.lando/cloudbeaver/workspace:/opt/cloudbeaver/workspace"
    portforward: true

proxy:
  adminer:
    - pma.mssql.localhost
  cloudbeaver:
    - pma2.mssql.localhost:8978

tooling:
  sqlcmd:
    service: database
    cmd: "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P he11oTHERE -C"

# Create your database:
# lando sqlcmd -Q "CREATE DATABASE database1;"
#
# Access the MSSQL via "PROJECTNAME_database_1" on port "1433" username "sa" password "he11oTHERE".
# Access externally with your IP and port displayed on lando info. You also need bindAddress: 0.0.0.0 in global Lando config, see https://docs.lando.dev/config/security.html#_1-changing-the-bind-address
#
# SQL cli example:
# lando sqlcmd -d database1 -C -Q "SELECT TOP (50) * FROM [dbo].[test_table1]"

# For cloudbeaver create a user cbadmin with password cBadmin0 on http://pma2.mssql.localhost/#/admin
